import { Raleway } from "next/font/google";
import "./globals.css";

const raleway = Raleway({ subsets: ["latin"] });

export const metadata = {
  title: "Quote | Random",
  description: "Generated by quotes random",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${raleway.className}`}>

      <section className="h-screen overflow-hidden">
          {children}
      </section>


      </body>
    </html>
  );
}
